version: 2
registries:
  npm-registry-packagecloud-io-meilleursagents-ma-prod-npm:
    type: npm-registry
    url: https://packagecloud.io/meilleursagents/ma-prod/npm
    token: "${{secrets.NPM_REGISTRY_PACKAGECLOUD_IO_MEILLEURSAGENTS_MA_PROD_NPM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  target-branch: dependencies_update
  ignore:
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.27.1
    - 5.28.0
    - 5.30.0
    - 5.31.2
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
  commit-message:
    prefix: chore
    include: scope
  registries:
  - npm-registry-packagecloud-io-meilleursagents-ma-prod-npm
