---

# https://dependabot.com/docs/config-file/

version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    target_branch: "dependencies_update"
    update_schedule: "weekly"
    commit_message:
      prefix: "chore"
      include_scope: true
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
