name: Publish Package

on:
  push:
    branches:
    - master
    tags:
    - v[0-9]+\.[0-9]+\.[0-9]+
    paths:
    - package.json

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
